- package.json
Fix the issue of: "cannot publish private repository" by adding:
```json
"publishConfig": {
"access": "public"
}
```
To the package.json
> fix(package): added missing publish access to semantic release

- www/docusaurus.config.js
Fixed twitter link, added my linkedin and changed topic name to "About maintainer" instead "Community".
> docs(docusaurus): added more info about maintainer

- package-lock.json
- package.json
- src/frameworks/trpc/index.ts
- src/frameworks/trpc/trpc.framework.ts
- src/index.doc.ts
- test/frameworks/koa.framework.spec.ts
- test/frameworks/trpc.framework.spec.ts
- test/frameworks/utils.ts
- www/docs/main/frameworks/trpc.mdx
- www/docs/main/intro.mdx
- www/sidebars.js
This PR adds support to [tRPC](https://trpc.io/docs/) as Framework.
> feat(trpc): added support to framework trpc

- .github/workflows/docs.yml
- .github/workflows/pr.yml
- www/docs/main/frameworks/trpc.mdx
Added job to build docs before merge.
Also fixed broken link for sqs inside trpc documentation.
> hotfix/test: docs before merge

- .github/workflows/docs.yml
- www/docusaurus.config.js
> docs(docsearch): added support for docsearch crawler

- www/docs/main/adapters/aws/event-bridge.mdx
- www/docs/main/intro.mdx
Added more explanation about how to use Event Bridge with Schedule Expression.
> docs: improve event bridge

- .github/workflows/docs.yml
I accidentally remove the step to deploy to gh-pages after build the docs.
> ci(docs): fixed issue with not deploying docs

- src/adapters/azure/http-trigger-v4.adapter.ts
- test/adapters/azure/http-trigger.adapter.spec.ts
Accords [this issue](https://stackoverflow.com/a/11312272) on Stack Overflow, cookie keys should be case-sensitive.
In the previous code, I changed the key putting in lowercase and trim.
> fix(http-trigger-v4): make the parseCookie function be case sensitive

- .github/workflows/docs.yml
- .github/workflows/pr.yml
- www/.tool-versions
- www/blog/2022-07-17-updates-and-releases.mdx
- www/package-lock.json
- www/package.json
Adding a new article to the blog.
> docs(blog): added new article to the blog

- www/docusaurus.config.js
Just fix the base url of sitemap.xml
> docs(www): changed base url of sitemap

- www/docs/main/frameworks/trpc.mdx
> docs(trpc): fixed typo mistake

- src/adapters/aws/index.ts
- src/adapters/aws/s3.adapter.ts
- test/adapters/aws/s3.adapter.spec.ts
- test/adapters/aws/utils/events.ts
- test/adapters/aws/utils/s3.ts
- www/docs/main/adapters/aws/s3.mdx
- www/docs/main/intro.mdx
Added support for [AWS S3](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html) as event source.
> feat(s3): added s3 adapter to aws

- package-lock.json
- package.json
- src/frameworks/body-parser/base-body-parser.framework.ts
- src/frameworks/body-parser/index.ts
- src/frameworks/body-parser/json-body-parser.framework.ts
- src/frameworks/body-parser/raw-body-parser.framework.ts
- src/frameworks/body-parser/text-body-parser.framework.ts
- src/frameworks/body-parser/urlencoded-body-parser.framework.ts
- src/frameworks/fastify/helpers/no-op-content-parser.ts
- src/index.doc.ts
- test/frameworks/body-parser.framework.spec.ts
- www/docs/main/frameworks/helpers/body-parser.mdx
- www/docs/main/intro.mdx
> feat(body-parser): added body-parsers frameworks

- www/static/CNAME
Try fix issue with CNAME being reseted after every deployment.
> docs(cname): try to fix issue with cname everytime I deploy

- src/handlers/firebase/http-firebase.handler.ts
- test/handlers/http-firebase.handler.spec.ts
> fix(firebase): issue with body-parser internally in firebase environment

- src/handlers/firebase/http-firebase-v2.handler.ts
- src/handlers/firebase/http-firebase.handler.ts
- src/handlers/firebase/index.ts
- test/handlers/http-firebase-v2.handler.spec.ts
- www/docs/main/handlers/firebase.mdx
- www/docs/main/intro.mdx
Add support for Firebase Functions V2.
> feat: firebase v2

- www/docs/main/frameworks/helpers/lazy.mdx
Fixing a small typo at the helpers/lazy page
> docs(helpers): fixing a small typo

- www/docs/main/frameworks/apollo-server.mdx
Fixing typos and redirect links
> docs(apollo server): fixing some typos and redirect links

- README.md
- package.json
- src/adapters/aws/index.ts
- src/adapters/aws/request-lambda-edge.adapter.ts
- src/adapters/aws/s3.adapter.ts
- src/adapters/aws/sns.adapter.ts
- src/adapters/aws/sqs.adapter.ts
- src/handlers/aws/aws-stream.handler.ts
- src/network/utils.ts
- test/adapters/aws/request-lambda-edge.adapter.spec.ts
- vite.config.ts
- www/blog/2022-06-17-the-beginning.mdx
- www/docs/main/adapters/aws/lambda-edge.mdx
- www/docs/main/adapters/aws/s3.mdx
- www/docs/main/adapters/aws/sns.mdx
- www/docs/main/adapters/aws/sqs.mdx
- www/docs/main/intro.mdx
> feat: better lambda edge

- .github/workflows/release.yml
Updated how this lib do releases.
> ci(release): use release manager instead of merge-and-release

- benchmark/package-lock.json
- benchmark/package.json
Bump package version of benchmark
> chore(benchmark): bump package versions

- .github/workflows/codeql-analysis.yml
> ci(codeql): updated configuration

- .github/workflows/docs.yml
- .github/workflows/pr.yml
Bump version of Github Actions.
> ci(workflows): bump action versions

- .github/workflows/release.yml
Support for: https://docs.npmjs.com/generating-provenance-statements
> ci(release): added provenance during publish

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
Inspired by https://github.com/eslint/create-config/pull/57/files#diff-2c84033033d49186c63e6adcd705f63b11ae6814cd76c152c9c486d389fbccf3R19-R30
> ci(release): include all commits on release

- .github/workflows/release.yml
- release-please-config.json
> ci(release-please): try fix issues with release please config

- package.json
- tsup.config.ts
- www/blog/2023-12-25-dual-package-publish.mdx
Tiny issue related to the import of the package under `moduleResolution=node`.
> fix(dual-package-publish): issue with imports lib when moduleResoluton is node

- .github/workflows/pr.yml
- .github/workflows/release.yml
- www/blog/2023-12-25-dual-package-publish.mdx
It happens even in the best families (:
> fix: missing lib folder

- src/adapters/aws/alb.adapter.ts
- src/adapters/aws/api-gateway-v1.adapter.ts
- src/adapters/aws/api-gateway-v2.adapter.ts
- src/network/response.ts
- test/adapters/aws/alb.adapter.spec.ts
- test/adapters/aws/api-gateway-v1.adapter.spec.ts
- test/adapters/aws/api-gateway-v2.adapter.spec.ts
- test/issues/issue-165/transfer-encoding-chunked-support.spec.ts
- www/docs/main/adapters/aws/alb.mdx
- www/docs/main/adapters/aws/api-gateway-v1.mdx
- www/docs/main/adapters/aws/api-gateway-v2.mdx
> feat(network): support buffering transfer-encoding: chunked

- package-lock.json
- package.json
- src/frameworks/polka/index.ts
- src/frameworks/polka/polka.framework.ts
- src/index.doc.ts
- test/frameworks/body-parser.framework.spec.ts
- test/frameworks/cors.framework.spec.ts
- test/frameworks/polka.framework.spec.ts
- test/issues/issue-165/transfer-encoding-chunked-support.spec.ts
- tsup.config.ts
- www/docs/main/frameworks/polka.mdx
- www/sidebars.js
Inspired by https://github.com/tessellator/sveltekit-adapter-lambda/issues/2
> feat(frameworks): added support for polka

- www/docs/main/getting-started/installation.mdx
This PR updates npm install command from `npm run i --save @h4ad/serverless-adapter` to `npm i --save @h4ad/serverless-adapter`
- N/A This pull request links relevant issues as `Fixes #0000`
- N/A There are new or updated unit tests validating the change
- N/A Added documentation inside `www/docs/main` folder.
- N/A Included new files inside `index.doc.ts`.
> docs(getting-started): update npm install command
